### ISSUE TITLE
What is the license for this project?

### ISSUE THREAD

**Issue by kingpong** [cloudfoundry-community/slack-notification-resource#32]

**Comment by xanderrman** [comment]
hey @kingpong, because no license has been chosen for this repo as of yet, It would fall under the github terms of service found [here](https://help.github.com/articles/github-terms-of-service/#5-license-grant-to-other-users) and pasted below.  Hope this helps 👍 

Any Content you post publicly, including issues, comments, and contributions to other Users' repositories, may be viewed by others. By setting your repositories to be viewed publicly, you agree to allow others to view and "fork" your repositories (this means that others may make their own copies of your Content in repositories they control).

If you set your pages and repositories to be viewed publicly, you grant each User of GitHub a nonexclusive, worldwide license to access your Content through the GitHub Service, and to use, display and perform your Content, and to reproduce your Content solely on GitHub as permitted through GitHub's functionality. You may grant further rights if you adopt a license.
